# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bot-BasicBot-Pluggable-Module-WoWPVP
version:      0.02
version_from: lib/Bot/BasicBot/Pluggable/Module/WoWPVP.pm
installdirs:  site
requires:
    Bot::BasicBot::Pluggable::Module: 0
    Games::WoW::PVP:               0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
